import {
  Music,
  Cat,
  Guitar,
  Ghost,
  Sparkles,
  Star,
  Heart,
  Dog,
  Rabbit,
  Bird,
  Fish,
  Rocket,
  Flame,
  Zap,
} from "lucide-react";

export const CHARACTERS = {
  cat: { icon: Cat, name: "Kitty" },
  ghost: { icon: Ghost, name: "Ghosty" },
  sparkles: { icon: Sparkles, name: "Sparky" },
  star: { icon: Star, name: "Starry" },
  heart: { icon: Heart, name: "Lovely" },
  dog: { icon: Dog, name: "Puppy" },
  rabbit: { icon: Rabbit, name: "Bunny" },
  bird: { icon: Bird, name: "Birdy" },
  fish: { icon: Fish, name: "Fishy" },
  rocket: { icon: Rocket, name: "Rocket" },
  flame: { icon: Flame, name: "Fire" },
  zap: { icon: Zap, name: "Flash" },
};

const THEMES = {
  "pinky-girl": {
    primary: "pink",
    instrument: Music,
    colors: {
      bg: "bg-pink-100",
      bg50: "bg-pink-50",
      border: "border-pink-200",
      border100: "border-pink-100",
      text: "text-pink-600",
      text400: "text-pink-400",
      text500: "text-pink-500",
      btn: "bg-pink-500",
      btnHover: "hover:bg-pink-600",
      btn400: "bg-pink-400",
      btn400Hover: "hover:bg-pink-500",
      cloud: "text-pink-300",
      ring: "ring-pink-200",
      accent: "#fce4ec",
      shadow: "shadow-pink-200",
      modalBorder: "border-pink-100",
    },
  },
  "energy-yellow": {
    primary: "yellow",
    instrument: Guitar,
    colors: {
      bg: "bg-yellow-100",
      bg50: "bg-yellow-50",
      border: "border-yellow-200",
      border100: "border-yellow-100",
      text: "text-yellow-600",
      text400: "text-yellow-400",
      text500: "text-yellow-500",
      btn: "bg-yellow-500",
      btnHover: "hover:bg-yellow-600",
      btn400: "bg-yellow-400",
      btn400Hover: "hover:bg-yellow-500",
      cloud: "text-yellow-300",
      ring: "ring-yellow-200",
      accent: "#fef3c7",
      shadow: "shadow-yellow-200",
      modalBorder: "border-yellow-100",
    },
  },
  "icy-blue": {
    primary: "blue",
    instrument: Music,
    colors: {
      bg: "bg-blue-100",
      bg50: "bg-blue-50",
      border: "border-blue-200",
      border100: "border-blue-100",
      text: "text-blue-600",
      text400: "text-blue-400",
      text500: "text-blue-500",
      btn: "bg-blue-500",
      btnHover: "hover:bg-blue-600",
      btn400: "bg-blue-400",
      btn400Hover: "hover:bg-blue-500",
      cloud: "text-blue-300",
      ring: "ring-blue-200",
      accent: "#e0f2fe",
      shadow: "shadow-blue-200",
      modalBorder: "border-blue-100",
    },
  },
  "fresh-green": {
    primary: "emerald",
    instrument: Music,
    colors: {
      bg: "bg-emerald-100",
      bg50: "bg-emerald-50",
      border: "border-emerald-200",
      border100: "border-emerald-100",
      text: "text-emerald-600",
      text400: "text-emerald-400",
      text500: "text-emerald-500",
      btn: "bg-emerald-500",
      btnHover: "hover:bg-emerald-600",
      btn400: "bg-emerald-400",
      btn400Hover: "hover:bg-emerald-500",
      cloud: "text-emerald-300",
      ring: "ring-emerald-200",
      accent: "#d1fae5",
      shadow: "shadow-emerald-200",
      modalBorder: "border-emerald-100",
    },
  },
  "dreamy-violet": {
    primary: "violet",
    instrument: Music,
    colors: {
      bg: "bg-violet-100",
      bg50: "bg-violet-50",
      border: "border-violet-200",
      border100: "border-violet-100",
      text: "text-violet-600",
      text400: "text-violet-400",
      text500: "text-violet-500",
      btn: "bg-violet-500",
      btnHover: "hover:bg-violet-600",
      btn400: "bg-violet-400",
      btn400Hover: "hover:bg-violet-500",
      cloud: "text-violet-300",
      ring: "ring-violet-200",
      accent: "#ede9fe",
      shadow: "shadow-violet-200",
      modalBorder: "border-violet-100",
    },
  },
  "passion-orange": {
    primary: "orange",
    instrument: Music,
    colors: {
      bg: "bg-orange-100",
      bg50: "bg-orange-50",
      border: "border-orange-200",
      border100: "border-orange-100",
      text: "text-orange-600",
      text400: "text-orange-400",
      text500: "text-orange-500",
      btn: "bg-orange-500",
      btnHover: "hover:bg-orange-600",
      btn400: "bg-orange-400",
      btn400Hover: "hover:bg-orange-500",
      cloud: "text-orange-300",
      ring: "ring-orange-200",
      accent: "#ffedd5",
      shadow: "shadow-orange-200",
      modalBorder: "border-orange-100",
    },
  },
};


export default THEMES;
